# Generated by Django 3.0.5 on 2020-08-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.BooleanField(default=False),
        ),
    ]
