# Generated by Django 3.0.5 on 2020-05-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_auto_20200524_1534'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
    ]
