# Generated by Django 3.0.5 on 2020-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0004_auto_20200524_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
