# Generated by Django 3.0.5 on 2020-05-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0005_auto_20200524_1538'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='CartItem',
        ),
    ]
