# Generated by Django 3.0.5 on 2020-08-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0005_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_goods.Operator'),
        ),
    ]
