# Generated by Django 3.0.5 on 2020-08-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0006_product_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'tarif',
                'verbose_name_plural': 'tarifs',
                'ordering': ('name',),
            },
        ),
    ]
