# Generated by Django 3.0.5 on 2020-08-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0006_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='operator',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_goods.Operator'),
        ),
    ]
