# Generated by Django 3.0.5 on 2020-08-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0007_product_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operator',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_goods.Operator'),
        ),
    ]
