# Generated by Django 3.0.5 on 2020-08-22 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0007_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tarif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_goods.Tarif'),
        ),
    ]
