# Generated by Django 3.0.5 on 2020-08-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0008_product_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tarif',
            name='free_gb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarif',
            name='free_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarif',
            name='home_tax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarif',
            name='line_rental',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarif',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_goods.Operator'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='out_tax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarif',
            name='stationary_tax',
            field=models.IntegerField(default=0),
        ),
    ]
