# Generated by Django 3.0.5 on 2020-08-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0009_auto_20200816_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_goods.Operator'),
        ),
    ]
