# Generated by Django 3.0.5 on 2020-08-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0010_auto_20200816_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
    ]
