# Generated by Django 3.0.5 on 2020-08-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0011_product_com_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nfc',
            field=models.BooleanField(default=False),
        ),
    ]
