# Generated by Django 3.0.5 on 2020-08-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0014_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sensor',
            field=models.ManyToManyField(blank=True, null=True, to='app_goods.Sensor'),
        ),
    ]
