# Generated by Django 3.0.5 on 2020-08-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0015_product_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='water_resistant',
            field=models.BooleanField(default=False),
        ),
    ]
