# Generated by Django 3.0.5 on 2020-08-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0016_product_water_resistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sensor',
            field=models.ManyToManyField(blank=True, to='app_goods.Sensor'),
        ),
    ]
