# Generated by Django 3.0.5 on 2020-08-24 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0018_body_material_lace_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_goods.Body_material'),
        ),
        migrations.AddField(
            model_name='product',
            name='lace_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_goods.Lace_material'),
        ),
    ]
