# Generated by Django 3.0.5 on 2020-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0019_auto_20200824_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
