# Generated by Django 3.0.5 on 2020-08-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0020_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='os',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
