# Generated by Django 3.0.5 on 2020-08-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0022_auto_20200901_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sim_cards',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(max_length=250),
        ),
    ]
