# Generated by Django 3.0.5 on 2020-08-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0023_auto_20200901_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biometrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'lace_material',
                'verbose_name_plural': 'lace_materials',
                'ordering': ('name',),
            },
        ),
    ]
