# Generated by Django 3.0.5 on 2020-08-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0025_auto_20200901_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometrics',
            name='slug',
        ),
    ]
