# Generated by Django 3.0.5 on 2020-08-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0026_remove_biometrics_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'internet',
                'verbose_name_plural': 'internet',
                'ordering': ('name',),
            },
        ),
    ]
