# Generated by Django 3.0.5 on 2020-08-31 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0027_internet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_goods.Internet'),
        ),
    ]
