# Generated by Django 3.0.5 on 2020-08-31 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0028_product_internet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='battery',
            new_name='com_types',
        ),
        migrations.RemoveField(
            model_name='product',
            name='com_type',
        ),
    ]
