# Generated by Django 3.0.5 on 2020-08-31 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0029_auto_20200901_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='internet',
        ),
    ]
