# Generated by Django 3.0.5 on 2020-08-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0032_security_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='com_types',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nfc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='water_resistant',
        ),
        migrations.AddField(
            model_name='product',
            name='com_type',
            field=models.ManyToManyField(blank=True, to='app_goods.Com_type'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='security_class',
            field=models.ManyToManyField(blank=True, to='app_goods.Security_class'),
        ),
    ]
