# Generated by Django 3.0.5 on 2020-08-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0033_auto_20200901_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nav',
            field=models.BooleanField(default=True),
        ),
    ]
