# Generated by Django 3.0.5 on 2020-09-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0034_product_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_color',
            field=models.BooleanField(default=True),
        ),
    ]
