# Generated by Django 3.0.5 on 2020-09-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0035_product_display_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_features',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
