# Generated by Django 3.0.5 on 2020-09-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0036_product_additional_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='gb_tax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarif',
            name='sms',
            field=models.IntegerField(default=0),
        ),
    ]
