# Generated by Django 3.0.5 on 2020-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0037_auto_20200903_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
