# Generated by Django 3.0.5 on 2020-09-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0038_auto_20200903_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
