# Generated by Django 3.0.5 on 2020-09-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0039_auto_20200903_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
