# Generated by Django 3.0.5 on 2020-09-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0040_cartitem_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='brand',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
