# Generated by Django 3.0.5 on 2020-09-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_auto_20200914_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='BIN',
            new_name='bank_account',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='account',
            new_name='bin',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='tax_id',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='entity',
            name='tax_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
