# Generated by Django 3.0.5 on 2020-09-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_auto_20200914_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='building',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='office',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='region',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='street',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='person',
            name='appartment',
        ),
        migrations.RemoveField(
            model_name='person',
            name='building',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='region',
        ),
        migrations.RemoveField(
            model_name='person',
            name='street',
        ),
        migrations.RemoveField(
            model_name='person',
            name='zip_code',
        ),
    ]
