# Generated by Django 3.0.5 on 2020-09-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0005_auto_20200915_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
