# Generated by Django 3.0.5 on 2020-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
        migrations.AlterField(
            model_name='order',
            name='appartment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='building',
            field=models.CharField(max_length=50),
        ),
    ]
