# Generated by Django 3.0.5 on 2020-09-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0004_order_corporate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
