# Generated by Django 3.0.5 on 2020-10-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0007_auto_20201004_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
